### PR TITLE
Update French difficulty label

### PR DESCRIPTION
**Pull request by Krabator**
These modifications only impact the French translation of the difficulty in SCS.
The present translation does not express the difficulty increase between each level of difficulty.
I have adapted the difficulty label to show the difficulty ramp up.

The modifications are visible in the game option menu and in the difficulty fine tuning panel IG.

Present translation : Défaut, Mode Histoire, Facile, Normal, Règle de base, Difficile, Très Difficile, Succession de Bhaal, Cœur de Furie
Proposed translation : Défaut, Basique, Améliorée, Tactique, Difficile, Très Difficile, Démentielle, Succession de Bhaal, Cœur de Furie

french diff translation

### CODE REVIEW

**Comment by mleduque** [comment]
I see you rewrote the files in  UTF8 (from cp1252 probably).
Has this been tested on original BG2?
Using utf8 as input is generally better but requires (I think) special handling in the mod to convert back to the original charset for the original engines? I may be wrong but checking wouldn't hurt.

**Comment by Krabator** [comment]
Hello,
I just remember that I tested my translation modifdication on the enhanced edition.
I don't have the possibility to test on the original support.

**Comment by DavidMWWallace** [comment]
I'd rather keep translation updates centralized - I can't check individual ones since I don't speak French myself.

**Comment by Jazira33** [comment]
Salut @Krabator, je vais étudier tes suggestions pour la v35. À l'origine, j'avais essayé de coller un maximum aux noms des presets de difficulté déjà existant en jeu, d'où les petites nuances, mais c'est en effet peut-être pas le plus judicieux. Merci. :)

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

Hi @Krabator, I'll study your suggestions for v35. Originally, I'd tried to stick as closely as possible to the names of the difficulty presets that already exist in the game, hence the small nuances, but maybe that's not the best idea. Thanks. :)

**Pull request closed without merging**
