### PR TITLE
Update Polish translation

### PR DESCRIPTION
**Pull request by tomasz1986**
1) caster_shared.tra, initial.tra, sfo.tra, shared.tra, ulcaster.tra:
   translation fixes and additions

1) doppelganger.tra: a new file with translated strings

3) leveller.tra, lib.tra: The strings listed in the two files currently
   are completely unrelated to the strings used in the English version
   of the files. As a result, the components using them in the game are
   completely broken (especially the leveller), as the text does not
   match the content. Therefore, replace the currently listed strings
   with the English ones, and translate the new strings from scratch.

4) setup.tra: The current translation of the file is incomplete and uses
   several outdated strings that do not match their English
   counterparts. Thus, add and translate the missing strings, update the
   current ones to match the English version, and fix several others to
   use a more natural translation.

5) undead.tra: Remove the current strings from the file, as they have
   text completely different from the English version, which will make
   it incomprehensible when shown in the game. Let us use the English
   strings for now, and do the actual translation later.

Signed-off-by: Tomasz Wilczyński <twilczynski@naver.com>

### CODE REVIEW

**Comment by tomasz1986** [comment]
I am also in the midst of translating `difficulty.tra`, but it will probably take some time, as there is a lot of text to translate, and I need to often re-check all the creature names, abilities, etc. to match the names actually used in the games. Once finished, I am going to do a separate pull request for the file.

**Comment by lukasz-pekala** [comment]
@tomasz1986  You probably need to convert these files to UTF-8 to display polish diacritics correctly

**Comment by lukasz-pekala** [comment]
@101 = ~Paralysation eyestalk destroyed~
@102 = ~Fear eyestalk destroyed~
@103 = ~Domination eyestalk destroyed~
@104 = ~Wounding eyestalk destroyed~
@105 = ~Charm eyestalk destroyed~
@106 = ~Petrification eyestalk destroyed~
@107 = ~Death-ray eyestalk destroyed~
@108 = ~Slowing eyestalk destroyed~
@109 = ~Telekinesis eyestalk destroyed~
@110 = ~Central eye damaged~
@111 = ~Lightning eyestalk destroyed~
@112 = ~Burning eyestalk destroyed~
@113 = ~Freezing eyestalk destroyed~
@114 = ~Magic-Missile eyestalk destroyed~
@115 = ~Enervation eyestalk destroyed~

From beholder.tra are probably missing too

**Comment by Roberciiik** [comment]
Hi @tomasz1986 I opened pull request #29 containing general Polish translations update. I found some useful translations from your PR, so I've included them in my PR. I hope you're OK with that. In fact, this PR can be closed. Thanks for your work.

**Comment by tomasz1986** [comment]
> Hi @tomasz1986 I opened pull request #29 containing general Polish translations update. I found some useful translations from your PR, so I've included them in my PR. I hope you're OK with that. In fact, this PR can be closed. Thanks for your work.

Yeah, let's close this one. Unfortunately, I didn't have time to properly finish the translation then, and the PR has been left in an incomplete state ever since. I'm sorry about that. Please re-use any of my translations as you see fit.

> @tomasz1986 You probably need to convert these files to UTF-8 to display polish diacritics correctly

We don't want to use UTF-8, because that would make the mod incompatible with the original (aka non-EE) versions of Baldur's Gate.

**Pull request closed without merging**
